spring.security.oauth2.client.registration.discord.client-id=1467015044511436830
spring.security.oauth2.client.registration.discord.client-secret=
spring.security.oauth2.client.registration.discord.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.discord.redirect-uri={baseUrl}/login/oauth2/code/discord
spring.security.oauth2.client.registration.discord.scope=identify,guilds

spring.security.oauth2.client.provider.discord.authorization-uri=https://discord.com/api/oauth2/authorize
spring.security.oauth2.client.provider.discord.token-uri=https://discord.com/api/oauth2/token
spring.security.oauth2.client.provider.discord.user-info-uri=https://discord.com/api/users/@me
spring.security.oauth2.client.provider.discord.user-name-attribute=username



spring.data.mongodb.uri=mongodb://konclips39_db_user:OtisDog%2355044@ac-bhamrcd-shard-00-00.t0jlpsf.mongodb.net:27017,ac-bhamrcd-shard-00-01.t0jlpsf.mongodb.net:27017,ac-bhamrcd-shard-00-02.t0jlpsf.mongodb.net:27017/?ssl=true&replicaSet=atlas-f3d8om-shard-0&authSource=admin&retryWrites=true&w=majority&tlsInsecure=true
spring.data.mongodb.database=yuihara